# Installs dependencies for CiCo managed by Anaconda.
# Advantage is you get working CUDA+cuDNN+pytorch+torchvison versions.
#
# TODO: you must additionally install nVidia drivers, eg. on Ubuntu linux
# `apt install nvidia-driver-440` (change the 440 for whatever version you need/have).
#
name: cico-env

channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.8
  - pip
  - cython
  - pytorch=1.10.1
  - torchvision=0.11.2
  - cudatoolkit=11.3.1
  - cudnn
  - matplotlib
  - git
  - pip:
    - opencv-python
    - pillow <7.0 # bug PILLOW_VERSION in torchvision, must be < 7.0 until torchvision is upgraded
    - pycocotools
    - PyQt5 # needed on KDE/Qt envs for matplotlib
    - fvcore
    - timm
    - scipy
    - einops


