MODEL:
  BACKBONE:
    CONV_BODY: 'ResNet50'
    PATH: 'resnet50-19c8e357.pth'
    ARGS: ([3, 4, 6, 3]),
    SELECTED_LAYERS: [1, 2, 3]
    PRED_SCALES: [[24], [48], [96], [192], [384]]
    PRED_ASPECT_RATIOS: [[[1, 0.5, 2]], [[1, 0.5, 2]], [[1, 0.5, 2]], [[1, 0.5, 2]], [[1, 0.5, 2]]]

  FPN:
    NUM_FEATURES: 256
    USE_CONV_DOWNSAMPLE: True
    NUM_DOWNSAMPLE: 2

  PREDICTION_HEADS:
    USE_DIoU: True
    USE_PREDICTION_MATCHING: True
    CUBIC_MODE: False
    CUBIC_CORRELATION_MODE: False
    # INITIALIZATION: reduced or inflated
    CUBIC_MODE_WITH_INITIALIZATION: 'inflated'

  BOX_HEADS:
    TRAIN_BOXES: True
    TOWER_LAYERS: 4
    TRAIN_CENTERNESS: True

  CLASS_HEADS:
    TRAIN_CLASS: True
    TOWER_LAYERS: 4
    USE_FOCAL_LOSS: True
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2

  TRACK_HEADS:
    TRAIN_TRACK: True
    TRACK_DIM: 64
    TOWER_LAYERS: 4
    LOSS_ALPHA: 5
    TRACK_BY_GAUSSIAN: False
    CROP_WITH_PRED_MASK: False
    MATCH_COEFF: [0, 1, 1, 0]

  MASK_HEADS:
    TRAIN_MASKS: True
    MASK_DIM: 16
    TOWER_LAYERS: 4
    PROTO_SRC: [0, 1, 2]
    PROTO_NET: ((256, 3, 1), (256, 3, 1), (256, 3, 1), (None, -2, ))
    PROTO_CROP: True
    PROTO_CROP_WITH_PRED_BOX: False
    LOSS_WITH_OIR_SIZE: False
    LOSS_WITH_DICE_COEFF: False
    USE_SEMANTIC_SEGMENTATION_LOSS: False
    PROTO_COEFF_OCCLUSION: False

INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
  MULTISCALE_TRAIN: False
  PRESERVE_ASPECT_RATIO: True
  SIZE_DIVISOR: 32

DATASETS:
  TYPE: 'vis'
  NUM_CLASSES: 40
  TRAIN: 'train_YouTube_VOS2019_dataset'
  VALID_SUB: 'valid_sub_YouTube_VOS2019_dataset'
  VALID: 'valid_YouTube_VOS2019_dataset'
  TEST: 'test_YouTube_VOS2019_dataset'

SOLVER:
  IMS_PER_BATCH: 8
  NUM_CLIP_FRAMES: 1
  LR: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1
  LR_STEPS: (8, 10)
  MAX_EPOCH: 12
  LR_WARMUP_UNTIL: 500
  SAVE_INTERVAL: 5000

TEST:
  IMS_PER_BATCH: 1
  NUM_CLIP_FRAMES: 1
  DETECTIONS_PER_IMG: 100
  NMS_IoU_THRESH: 0.5
  NMS_CONF_THRESH: 0.1
  NMS_WITH_BIoU: True
  NMS_WITH_MIoU: False

OUTPUT_DIR: 'weights/YTVIS2019/'
NAME: 'r50_base'
