STMask:
  FC:
    USE_FCA: True
    FCA_CONV_KERNELS: [[3,3], [3,5], [5,3]]
    USE_FCB: True
    FCB_USE_PRED_OFFSET: True
    FCB_USE_DCN_CLASS: True
    FCB_USE_DCN_TRACK: False
    FCB_USE_DCN_MASK: False

  T2S_HEADS:
    TEMPORAL_FUSION_MODULE: True
    T2S_WITH_ROIALIGN: True
    CORRELATION_PATCH_SIZE: 5
    CORRELATION_SELECTED_LAYER: 1
    TRAIN_BOXSHIFT: True
    BOXSHIFT_ALPHA: 1
    TRAIN_MASKSHIFT: False
    MASKSHIFT_ALPHA: 6.125
    BOXSHIFT_WITH_PRED_BOX: False
    FORWARD_FLOW: True
    BACKWARD_FLOW: False