MODEL:
  BACKBONE:
    CONV_BODY: 'ResNet50'
    PATH: 'STMask_resnet50_coco_960_46_340000.pth'
    ARGS: ([3, 4, 6, 3],),
    SELECTED_LAYERS: [1, 2, 3]
    PRED_SCALES: [[24], [48], [96], [192], [384]]
    PRED_ASPECT_RATIOS: [[[ 1, 0.5,  2 ]]] * 5

  FPN:
    NUM_FEATURES: 256
    USE_CONV_DOWNSAMPLE: True
    NUM_DOWNSAMPLE: 2

  PREDICTION_HEADS:
    USE_DIoU: True
    CUBIC_MODE: False
    CUBIC_CORRELATION_MODE: False

  BOX_HEADS:
    TRAIN_BOXES: True
    TRAIN_CENTERNESS: True

  CLASS_HEADS:
    TRAIN_CLASS: True
    USE_FOCAL_LOSS: True
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2

  TRACK_HEADS:
    TRAIN_TRACK: True
    TRACK_DIM: 64
    LOSS_ALPHA: 5
    MATCH_COEFF: [0, 1, 1, 0]

  MASK_HEADS:
    TRAIN_MASKS: True
    MASK_DIM: 32
    PROTO_SRC: [0]
    PROTO_NET: [(256, 3, {'padding': 1})] * 3 + [(None, -2, {})]
    PROTO_CROP: True
    PROTO_CROP_WITH_PRED_BOX: False
    LOSS_WITH_OIR_SIZE: False
    LOSS_WITH_DICE_COEFF: False

INPUT:
  MIN_SIZE_TRAIN: (360,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 360
  MAX_SIZE_TEST: 640
  MULTISCALE_TRAIN: False
  PRESERVE_ASPECT_RATIO: True
  SIZE_DIVISOR: 32

DATASETS:
  TRAIN: 'train_YouTube_VOS2019_dataset'
  VALID_SUB: 'valid_sub_YouTube_VOS2019_dataset'
  VALID: 'valid_YouTube_VOS2019_dataset'
  TEST: 'test_YouTube_VOS2019_dataset'

SOLVER:
  IMS_PER_BATCH: 8
  NUM_CLIP_FRAMES: 2
  LR: 0.001
  LR_STEPS: (8, 10)
  MAX_EPOCH: 12
  SAVE_INTERVAL: 5000

TEST:
  IMS_PER_BATCH: 1
  NUM_CLIP_FRAMES: 1
  DETECTIONS_PER_IMG: 100
  NMS_IoU_THRESH: 0.5
  NMS_CONF_THRESH: 0.1
  NMS_WITH_BIoU: True
  NMS_WITH_MIoU: True
