MODEL:
  BACKBONE:
    CONV_BODY: 'ResNet50'
    PATH: 'resnet50-19c8e357.pth'
    ARGS: ([3, 4, 6, 3],),
    SELECTED_LAYERS: [1, 2, 3]
    PRED_SCALES: [[24], [48], [96], [192], [384]]
    PRED_ASPECT_RATIOS: [[[ 1, 0.5,  2 ]]] * 5

  FPN:
    NUM_FEATURES: 256
    USE_CONV_DOWNSAMPLE: True
    NUM_DOWNSAMPLE: 2

  PREDICTION_HEADS:
    USE_DIoU: True

  BOX_HEADS:
    TRAIN_BOXES: True
    TRAIN_CENTERNESS: True

  CLASS_HEADS:
    TRAIN_CLASS: True
    USE_FOCAL_LOSS: True
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2

  TRACK_HEADS:
    TRAIN_TRACK: False

  MASK_HEADS:
    TRAIN_MASKS: True
    MASK_DIM: 32
    PROTO_SRC: [0, 1, 2]
    PROTO_NET: [(256, 3, {'padding': 1})] * 3 + [(None, -2, {})]
    PROTO_CROP: True
    PROTO_CROP_WITH_PRED_BOX: False
    LOSS_WITH_OIR_SIZE: False
    LOSS_WITH_DICE_COEFF: False
    USE_SEMANTIC_SEGMENTATION_LOSS: True

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  MULTISCALE_TRAIN: True
  PRESERVE_ASPECT_RATIO: True
  SIZE_DIVISOR: 32

DATASETS:
  TRAIN: 'coco2017_train_dataset'
  VALID_SUB: 'coco2017_valid_dataset'
  VALID: 'coco2017_valid_dataset'
  TEST: 'coco2017_testdev_dataset'

SOLVER:
  IMS_PER_BATCH: 16
  NUM_CLIP_FRAMES: 1
  LR: 0.001
  LR_STEPS: (20, 40, 46, 50)
  MAX_EPOCH: 54
  SAVE_INTERVAL: 5000

TEST:
  IMS_PER_BATCH: 1
  NUM_CLIP_FRAMES: 1
  DETECTIONS_PER_IMG: 200
  NMS_CONF_THRESH: 0.05
  NMS_WITH_BIoU: True
  NMS_WITH_MIoU: False
