MODEL:

  PREDICTION_HEADS:
    CUBIC_MODE: True
    CUBIC_CORRELATION_MODE: False
    # INITIALIZATION: reduced or inflated
    CUBIC_MODE_WITH_INITIALIZATION: 'inflated'

SOLVER:
  IMS_PER_BATCH: 8
  NUM_CLIP_FRAMES: 2
  LR: 0.001
  LR_STEPS: (8, 10)
  MAX_EPOCH: 12
  SAVE_INTERVAL: 5000

TEST:
  IMS_PER_BATCH: 1
  NUM_CLIP_FRAMES: 2

