MODEL:
  BACKBONE:
    SWINT:
      engine: True
      patch_size: 4
      in_chans: 3
      embed_dim: 96
      depths: [2, 2, 6, 2]
      num_heads: [3, 6, 12, 24]
      window_size: 7
      mlp_ratio: 4.
      qkv_bias: True
      qk_scale: None
      drop_rate: 0.
      attn_drop_rate: 0.
      drop_path_rate: 0.1
      ape: False
      patch_norm: True
      out_indices: (0, 1, 2, 3)
      frozen_stages: -1
      use_checkpoint: False
      path: 'swin_tiny_patch4_window7_224.pth'

  FPN:
    NUM_FEATURES: 192
    USE_CONV_DOWNSAMPLE: True
    NUM_DOWNSAMPLE: 2

OUTPUT_DIR: 'weights/'
NAME: 'swint_base'
